"""initial_schema

Revision ID: 9153fb5d44ed
Revises: 
Create Date: 2026-03-24 20:02:39.727817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9153fb5d44ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cooperatives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contribution_amount', sa.BigInteger(), nullable=False),
    sa.Column('due_day_offset', sa.Integer(), nullable=False),
    sa.Column('created_by_member_id', sa.UUID(), nullable=True),
    sa.Column('pool_balance', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=True),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_phone_number'), 'members', ['phone_number'], unique=True)
    op.create_table('conversation_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('active_cooperative_id', sa.UUID(), nullable=True),
    sa.Column('current_flow', sa.String(length=50), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('flow_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_active', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['active_cooperative_id'], ['cooperatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_sessions_phone_number'), 'conversation_sessions', ['phone_number'], unique=True)
    op.create_table('coop_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('cooperative_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('member','exco')", name='ck_coop_members_role'),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperatives.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'cooperative_id')
    )
    op.create_table('coop_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cooperative_id', sa.UUID(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('anchor_date', sa.Date(), nullable=False),
    sa.Column('due_day_offset', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("frequency IN ('weekly','biweekly','triweekly','monthly','bimonthly','quarterly','yearly')", name='ck_coop_schedules_frequency'),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('join_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('cooperative_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redeemed_by_member_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('member','exco')", name='ck_join_codes_role'),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperatives.id'], ),
    sa.ForeignKeyConstraint(['redeemed_by_member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('pending_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('cooperative_id', sa.UUID(), nullable=False),
    sa.Column('period_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending','paid','failed','invalidated')", name='ck_pending_transactions_status'),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperatives.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_transactions_reference'), 'pending_transactions', ['reference'], unique=True)
    op.create_table('pools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cooperative_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_amount', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperatives.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('withdrawals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cooperative_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('authorized_by_member_id', sa.UUID(), nullable=False),
    sa.Column('pool_balance_after', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['authorized_by_member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contribution_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cooperative_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperatives.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['coop_schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cooperative_id', 'period_number')
    )
    op.create_index('idx_contribution_periods_coop_due', 'contribution_periods', ['cooperative_id', 'due_date'], unique=False)
    op.create_table('contributions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('cooperative_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=False),
    sa.Column('pool_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('unpaid','paid')", name='ck_contributions_status'),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperatives.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['contribution_periods.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'period_id')
    )
    op.create_table('reminder_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("stage IN ('7_day','3_day','1_day','due_date','1_week_overdue','2_weeks_overdue')", name='ck_reminder_log_stage'),
    sa.CheckConstraint("status IN ('pending','sent','cancelled')", name='ck_reminder_log_status'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['contribution_periods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'period_id', 'stage')
    )
    op.create_index('idx_reminder_log_scheduled', 'reminder_log', ['scheduled_at', 'status'], unique=False)
    
    op.create_foreign_key(
        'fk_cooperatives_created_by', 'cooperatives', 'members',
        ['created_by_member_id'], ['id'], use_alter=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_cooperatives_created_by', 'cooperatives', type_='foreignkey')
    op.drop_index('idx_reminder_log_scheduled', table_name='reminder_log')
    op.drop_table('reminder_log')
    op.drop_table('contributions')
    op.drop_index('idx_contribution_periods_coop_due', table_name='contribution_periods')
    op.drop_table('contribution_periods')
    op.drop_table('withdrawals')
    op.drop_table('pools')
    op.drop_index(op.f('ix_pending_transactions_reference'), table_name='pending_transactions')
    op.drop_table('pending_transactions')
    op.drop_table('join_codes')
    op.drop_table('coop_schedules')
    op.drop_table('coop_members')
    op.drop_index(op.f('ix_conversation_sessions_phone_number'), table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    op.drop_index(op.f('ix_members_phone_number'), table_name='members')
    op.drop_table('members')
    op.drop_table('cooperatives')
    # ### end Alembic commands ###